definitions:
  entities.Person:
    properties:
      age:
        type: integer
      created_at:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
      updated_at:
        type: string
    required:
    - name
    - surname
    type: object
info:
  contact: {}
paths:
  /people/{id}:
    get:
      consumes:
      - application/json
      description: Get detailed information about a person by their ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved person
          schema:
            $ref: '#/definitions/entities.Person'
        "400":
          description: Invalid ID format
          schema:
            type: string
        "404":
          description: Person not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get person by ID
      tags:
      - people
swagger: "2.0"
